import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from 'react';
import ImageCanvas from "../components/ImageCanvas";


const Home: NextPage = () => {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    // todo: get link fro user and do a request to get the json data
    fetch("output.json")
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, []);

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No data</p>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* todo: center canvas */}
        {data && !isLoading && <ImageCanvas data={data}></ImageCanvas>}
      </main>
    </>
  );
};

export default Home;
