import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import ImageCanvas from "../../components/ImageCanvas";
import Head from "next/head";

export default function Page() {
  const router = useRouter();
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    if (!router.isReady) return;

    const url = `https://api.onepanel.app/v2/chapter/${router.query.hash}`;
    // const url = `http://localhost:8000/v2/chapter/${router.query.hash}`;

    fetch(url, {
      mode: "cors",
      method: "GET",
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Content-Type": "application/json",
      },
    })
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      });
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>OnePanel Reader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#64de9f] to-[#13aeae]">
        {data && !isLoading && <ImageCanvas data={data}></ImageCanvas>}
      </main>
    </>
  );
}
