import { useRouter } from "next/router";
import { useCallback, useEffect, useState } from "react";
import ImageCanvas from "../../components/ImageCanvas";
import Head from "next/head";
import LoadingComponent from "../../components/Loading";
import ErrorMessage from "../../components/ErrorMessage";
import { getChapter } from "../../lib/api";

export default function Page() {
  const router = useRouter();
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const loadChapter = useCallback(async () => {
    if (!router.isReady) return;
    const hash = Array.isArray(router.query.hash)
      ? router.query.hash[0]
      : router.query.hash;
    if (!hash) return;

    setLoading(true);
    setError(null);
    setData(null);
    try {
      setData(await getChapter(hash));
    } catch (error) {
      setError(
        error instanceof Error ? error.message : "Could not load the chapter.",
      );
    } finally {
      setLoading(false);
    }
  }, [router.isReady, router.query.hash]);

  useEffect(() => {
    void loadChapter();
  }, [loadChapter]);

  return (
    <>
      <Head>
        <title>OnePanel Reader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-[#64de9f] to-[#13aeae]">
        {isLoading && <LoadingComponent />}
        {error && <ErrorMessage message={error} onRetry={loadChapter} />}
        {data && !isLoading && <ImageCanvas data={data}></ImageCanvas>}
      </main>
    </>
  );
}
